### ISSUE TITLE
MSYS2 Compilation Error

### ISSUE THREAD

**Issue by cursedUs64-git** [Fluvian/tpp#108]
qemu-irix isn't supported on MSYS2, but i dont think it could be the cause of the error.

`C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\Awesome\AppData\Local\Temp\cclPsZvP.o:skyconv.c:(.text+0x156): undefined reference to "realpath"
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\Awesome\AppData\Local\Temp\cclPsZvP.o:skyconv.c:(.text+0x459): undefined reference to "realpath"
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\Awesome\AppData\Local\Temp\cclPsZvP.o:skyconv.c:(.text+0x68c): undefined reference to "realpath"
collect2.exe: error: ld returned 1 exit status
make[1]: *** [Makefile:54: skyconv] Error 1
Traceback (most recent call last):
  File "/c/Users/Awesome/clone/tpp/./extract_assets.py", line 281, in <module>
    main()
  File "/c/Users/Awesome/clone/tpp/./extract_assets.py", line 156, in main
    subprocess.check_call(
  File "/usr/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-s', '-C', 'tools/', 'n64graphics', 'skyconv', 'mio0', 'aifc_decode']' returned non-zero exit status 2.
Makefile:123: *** Failed to extract assets.  Stop.`
maybe is it because all of the files in tools/ is for Linux only?
![Screenshot (1)](https://user-images.githubusercontent.com/110907873/234574950-916ecce3-153c-46ba-a41e-5eacb22027a6.png)

**Comment by cursedUs64-git** [comment]
Update: it compiles with vanilla src and ultrasm64 src

**Comment by cursedUs64-git** [comment]
should have used docker....?

**Comment by Fluvian** [comment]
Compilation on Windows is not supported.
