### ISSUE TITLE
[Help] How do i replace mario with luigi with the given luigi assets?

### ISSUE THREAD

**Issue by cursedUs64-git** [Fluvian/tpp#109]
I remember there was a git patch for it, but i cant find it and i want to do it manually.

**Comment by iProgramMC** [comment]
Here's where Mario is compiled in:
https://github.com/Fluvian/tpp/blob/main/actors/group0.c#L13

Here's where the Mario model is loaded. Change this to `RCP_LuigiHierarchy`.
https://github.com/Fluvian/tpp/blob/main/levels/scripts.c#L68

**Comment by cursedUs64-git** [comment]
Thank you.
