### ISSUE TITLE
CLOSED

### ISSUE THREAD

**Issue by indfibneiubdf** [Fluvian/tpp#110]

**Comment by indfibneiubdf** [comment]
How do I fix it

**Comment by indfibneiubdf** [comment]
Sir, I'm very sorry, I didn't type in the description because I thought the post was already self-explanatory and only realized it at after I made the post. I tried to edit the title, but it wouldn't let me. Do I just take it down and make a new post?

**Comment by iProgramMC** [comment]
No, you can however close the issue and create a new one.

**Comment by indfibneiubdf** [comment]
Ok, thanks.

**Comment by iProgramMC** [comment]
There is a "Close Issue" button which you, as the author of issue, can press. Please do.
