### ISSUE TITLE
Luigi crashes LLL and DDD

### ISSUE THREAD

**Issue by LunarNova12** [Fluvian/tpp#112]
I compiled TPP with the given luigi assets.  It mostly works, however, when entering LLL or DDD, using either the pause menu or painting, the game crashes with the error shown in the image. It's the same error for both LLL and DDD.

![Screenshot 2023-05-13 130012](https://github.com/Fluvian/tpp/assets/133529955/d2dbb156-c4cc-4a1b-b40e-dedf55d06290)

**Comment by Fluvian** [comment]
You're probably running out of memory. Seeing as this is not an issue with TPP itself, rather your modification, I will have to close this issue.
