### ISSUE TITLE
Failure to install build dependencies

### ISSUE THREAD

**Issue by Llaima4** [Fluvian/tpp#113]
Used the command shown in the readme:
![image](https://github.com/Fluvian/tpp/assets/100494379/42110cef-f61d-4088-b342-4132d97b05fb)

**Comment by cursedUs64-git** [comment]
Please do sudo apt update && sudo apt upgrade if you are running on wsl, if not, you still have to do the same thing.

**Comment by cursedUs64-git** [comment]
It could also be a firewall problem.

**Comment by Llaima4** [comment]
worked
