### ISSUE TITLE
No Mario SFX On Title Screen

### ISSUE THREAD

**Issue by megfan2008** [Fluvian/tpp#115]
So in the shoshinkai demo, you can hear beta mario's sfx on the title screen. for some reason this isnt in tpp.

https://cdn.discordapp.com/attachments/1108193889753497672/1128530093938069575/Super_Mario_64_Shoshinkai_1995_Title_screen.ogg

**Comment by notvillager64** [comment]
What do you mean? The Beta Mario SFX is on the title screen music.

**Comment by megfan2008** [comment]
Oh. i always only stay on the title screen for a few secs so thats why i didnt hear it.
