### ISSUE TITLE
Undefined references when importing level via Fast64

### ISSUE THREAD

**Issue by ghbbeep** [Fluvian/tpp#14]
Just an issue I came across out of curiosity.

mips-linux-gnu-ld: warning: dot moved backwards before `.buffers.noload'
mips-linux-gnu-ld: warning: dot moved backwards before `.buffers.noload'
mips-linux-gnu-ld: warning: dot moved backwards before `.buffers.noload'
mips-linux-gnu-ld: build/jp/levels/bitdw/script.o:(.data+0x1b0): undefined reference to `bitdw_area_1_collision'
mips-linux-gnu-ld: build/jp/levels/bitdw/script.o:(.data+0x1b8): undefined reference to `bitdw_area_1_macro_objs'
mips-linux-gnu-ld: build/jp/levels/bitdw/geo.o:(.data+0x2f0): undefined reference to `bitdw_dl_SketchUp_mesh_layer_1'
mips-linux-gnu-ld: build/jp/levels/bitdw/geo.o:(.data+0x2fc): undefined reference to `bitdw_dl_SketchUp_001_mesh_layer_1'
mips-linux-gnu-ld: build/jp/levels/bitdw/geo.o:(.data+0x308): undefined reference to `bitdw_dl_SketchUp_002_mesh_layer_1'
mips-linux-gnu-ld: build/jp/levels/bitdw/geo.o:(.data+0x314): undefined reference to `bitdw_dl_SketchUp_003_mesh_layer_1'
mips-linux-gnu-ld: build/jp/levels/bitdw/geo.o:(.data+0x320): undefined reference to `bitdw_dl_SketchUp_004_mesh_layer_1'
mips-linux-gnu-ld: build/jp/levels/bitdw/geo.o:(.data+0x32c): undefined reference to `bitdw_dl_SketchUp_005_mesh_layer_1'
mips-linux-gnu-ld: build/jp/levels/bitdw/geo.o:(.data+0x338): undefined reference to `bitdw_dl_SketchUp_006_mesh_layer_1'
mips-linux-gnu-ld: build/jp/levels/bitdw/geo.o:(.data+0x344): undefined reference to `bitdw_dl_SketchUp_007_mesh_layer_1'
mips-linux-gnu-ld: build/jp/levels/bitdw/geo.o:(.data+0x350): undefined reference to `bitdw_dl_SketchUp_008_mesh_layer_1'
mips-linux-gnu-ld: build/jp/levels/bitdw/geo.o:(.data+0x35c): undefined reference to `bitdw_dl_SketchUp_009_mesh_layer_1'
mips-linux-gnu-ld: build/jp/levels/bitdw/geo.o:(.data+0x3ec): undefined reference to `bitdw_dl_material_revert_render_settings'
make: *** [Makefile:592: build/jp/sm64.jp.elf] Error 1

**Comment by Fluvian** [comment]
That's an issue you caused.
