### ISSUE TITLE
Release Patch Doesn't Work

### ISSUE THREAD

**Issue by raccoonmario3** [Fluvian/tpp#15]
The release, posted at [https://github.com/Fluvian/tpp/releases/tag/first_release](url) doesn't work. I have tried applying the patch using multiple ROMs, and have of course tried using the original Japanese ROM as specified. I tried both .z64 and .n64 variants of the ROM, to no avail. I always get an error saying that the patch is not meant for the ROM I'm trying to use. This happens when using the FLIPS patcher as well as the online patcher linked at [https://hack64.net/tools/patcher.php](url). When I select "skip checksums," I am able to get a ROM, but it's a non-functioning, broken ROM that refuses to start. On Project 64, for example, it gives an infinite loop error.

**Comment by OriginalChris617** [comment]
Strange, it works for me just fine when using the Beat patcher with the Japanese .n64 ROM.

**Comment by raccoonmario3** [comment]
What is the checksum of your ROM?

**Comment by OriginalChris617** [comment]
I'll be honest, I have no idea how to check that.

**Comment by raccoonmario3** [comment]
When I tried using Beat, it just said that the Patch application failed. There are a number of online tools, such as [https://emn178.github.io/online-tools/md5_checksum.html](url), which will allow you to put in a file and get the checksum. Checksums are used to verify if two files are exactly the same. If even one byte is different, the checksum will be completely different.

**Comment by OriginalChris617** [comment]
Tried the tool. These were the results.
Separate SM64 ROM file checksum: 85d61f5525af708c9f1e84dce6dc10e9
TPP ROM: 18bceeec947ea35312fdbbb16803740d
Not sure which one you needed so I tried both.

**Comment by raccoonmario3** [comment]
It works now! The solution was to use the latest nointro SM64 original Japanese ROM. I was using a nointro ROM, but it was from an older version of the nointro set. My checksums for both the base ROM and the patched ROM now match yours.

**Comment by iProgramMC** [comment]
Feel free to close this issue if it's fixed.

**Comment by wijayodustin021** [comment]
It Works! Thanks Fluvian, MarioNova64, 64History (64Bot), and TPP's Channel.
