### ISSUE TITLE
The bridge in Lethal Lava Land nearing the only star in the level happens to be placed incorrectly.

### ISSUE THREAD

**Issue by ripoof** [Fluvian/tpp#16]
If I recall correctly, this is not supposed to be above the platform.
![image](https://user-images.githubusercontent.com/44599717/172758286-07e613f0-c48f-4768-858e-b7ef571a7848.png)

**Comment by xiartic** [comment]
![screen](https://user-images.githubusercontent.com/78692485/172762511-53ca2950-c957-4be6-86c9-d63358f014fc.PNG)
In this screenshot captured from a piece of footage. It appeared that the bridge actually used to be ever so slightly above the platform Mario's standing on.
