### ISSUE TITLE
Mario is able to stand on the sloped part in Lethal Lava Land.

### ISSUE THREAD

**Issue by ripoof** [Fluvian/tpp#18]
https://user-images.githubusercontent.com/44599717/172766703-6bba057e-15ba-4f15-8504-d1daa264d2a6.mp4

**Comment by iProgramMC** [comment]
You can stand there in the original game too. I see nothing wrong.
![image](https://user-images.githubusercontent.com/17717494/172769398-1cbdb2b1-b70d-462a-aa3a-266f3c0d9643.png)

**Comment by ripoof** [comment]
![image](https://user-images.githubusercontent.com/44599717/172771439-f0c13bee-aa28-4276-8c55-99d235cdaeb2.png)

**Comment by iProgramMC** [comment]
Interesting
