### ISSUE TITLE
TTM slide warp broken

### ISSUE THREAD

**Issue by crustman69** [Fluvian/tpp#21]
https://cdn.discordapp.com/attachments/845405298974130226/984433312921706526/sm64.jp_-_Project64_Dev-4.0.0.5811-8e5efea_2022-06-09_07-22-32_Trim.mp4

this should be pretty easy to fix so it's not really an issue

**Comment by Fluvian** [comment]
Please update your repository, the commit 710d4ca6f92c6177ed7989416043bb597a869fb7 fixes this.
