### ISSUE TITLE
Inside Castle UV Problem

### ISSUE THREAD

**Issue by GodlyGH** [Fluvian/tpp#25]
The below photo shows the UV being a bit wonky or slightly bent, I can't say the same for the latest hotfix as I haven't checked it out yet. 
![Screenshot_20220609_170419](https://user-images.githubusercontent.com/72700467/172866679-4d22a569-6d97-42ea-92b5-7da554c07232.jpg)

**Comment by Fluvian** [comment]
That is intended. 
![image](https://user-images.githubusercontent.com/61193101/172867263-73a5d5d6-90d9-4991-bb02-1a872492ed12.png)
![image](https://user-images.githubusercontent.com/61193101/172867174-a981e00a-7f0a-4cf3-b1d5-4c90b01e5c24.png)

**Comment by Fluvian** [comment]
![image](https://user-images.githubusercontent.com/61193101/172868025-3c2e90c3-5bad-438e-8262-3e81f8b665d8.png)
![image](https://user-images.githubusercontent.com/61193101/172868041-5dd79434-5de0-4ded-8395-f0bb1166cbdc.png)
