### ISSUE TITLE
Mario's Cannon Launch Movement Is Inaccurate

### ISSUE THREAD

**Issue by ghbbeep** [Fluvian/tpp#29]
When Mario is launched from a cannon in the SpaceWorld demo, he moves in a linear fashion. Attached is a diagram of what I mean.
![github thing](https://user-images.githubusercontent.com/77814425/172939891-5543ae9b-ce8a-4365-928c-27958bee6cc5.png)

**Comment by ghbbeep** [comment]
UPDATE: I found the footage with the cannon launch. Here you can see exactly what i'm talking about; no diagram needed.

https://youtu.be/ys723F9wiwU
Cannon Footage is at 11:05.

**Comment by Fluvian** [comment]
This was dealt with a long time ago already, press forward the entire time and you'll get the exact movement.
