### ISSUE TITLE
Error Compiling with docker on windows

### ISSUE THREAD

**Issue by YoshiFan501** [Fluvian/tpp#32]
I am having multiple errors using docker on windows. the first error was where it couldnt find ‘python3\r’, which was fixed by changing all the python files' EOL to unix and not windows.

Thes second bug I am encountering is the following over and over

cfe: Warning 594: o in #if or #elif
3.8
unknown command line option

with other random errors like

make: *** [build/us/src/engine/level_script.o] Error 1
Makefile:575: recipe for target 'build/us/src/engine/level_script.o' failed

make: *** [build/us/src/engine/behavior_script.o] Error 1
Makefile:575: recipe for target 'build/us/src/engine/behavior_script.o' failed

ending with
make: *** [build/us/src/engine/level_script.o] Error 1
Makefile:575: recipe for target 'build/us/src/engine/level_script.o' failed

Makefile:575: recipe for target 'build/us/src/engine/graph_node_manager.o' failed
make: *** [build/us/src/engine/graph_node_manager.o] Error 1

I am compiling with a US ROM, though I get the same errors with a JP rom. this is using the exact command in the readme.

![image](https://user-images.githubusercontent.com/1903751/172949776-ec495b0f-da2a-4dbd-8d8f-5ac2555d6ec2.png)

**Comment by Fluvian** [comment]
The Docker is really meant to only run on Linux, since you seem to be on Windows 11 I recommend installing [WSL2](https://docs.microsoft.com/en-us/windows/wsl/install) and then just follow the Linux instructions.

**Comment by YoshiFan501** [comment]
Will do! thank you

**Comment by iProgramMC** [comment]
FYI WSL1 works too. Use this if you don't want Hyper-V enabled (some applications are incompatible with it)
