### ISSUE TITLE
Bowser warp uses the wrong transition type

### ISSUE THREAD

**Issue by Hornet64** [Fluvian/tpp#39]
TPP is currently using a star shaped transition when going into the trapdoor leading to the bowser fight.
![image](https://user-images.githubusercontent.com/78374744/173114849-9ae75bfc-2e20-45f3-ba0c-b126e6e2ad81.png)

It should actually be using a circle shaped transition.
![image](https://user-images.githubusercontent.com/78374744/173114894-fd7f264c-5e26-4cc8-9731-663d3d42b0a9.png)

**Comment by xiartic** [comment]
https://trello.com/b/ngPd0V3j/tpp 

This difference was reported in the TODO.
