### ISSUE TITLE
Camera Glitch

### ISSUE THREAD

**Issue by Cappybowsy** [Fluvian/tpp#43]
i was in dire dire docks. I opened the map then the camera started to glitch. heres some screenshots:
![GLideN64__013](https://user-images.githubusercontent.com/107319411/173198613-f9187f38-2df0-4c6e-9c74-166717421ae6.png)

![GLideN64__012](https://user-images.githubusercontent.com/107319411/173198590-a4a6ed59-7ec3-4077-a452-549572404d7a.png)

**Comment by Fluvian** [comment]
None of this makes sense.

**Comment by xiartic** [comment]
Look at some footage to understand.
