### ISSUE TITLE
Beta WF Level incorrectly VU & Inaccurately Design (a little bit)

### ISSUE THREAD

**Issue by MasterNama17083** [Fluvian/tpp#51]
Hello, I found an inaccurate VU rock texture may be found.
![image](https://user-images.githubusercontent.com/80534869/173241751-10a1e0bb-1f6a-4eae-b0dd-1a0057246b4a.png)

Look closer to see better results:
![image](https://user-images.githubusercontent.com/80534869/173241852-962f2595-1ec8-4aa9-a9b8-87fd35a3e7b0.png)
why that rock texture looks stretched.

This SSK 95' Footage may be found original VU texture: (same time but no stretched is that texture)
![image](https://user-images.githubusercontent.com/80534869/173242523-391288d9-77fe-4621-999f-be50fe541f15.png)

And, There're many cuts of lines:
![image](https://user-images.githubusercontent.com/80534869/173242640-feee38de-98f1-423f-85df-c334f3e2ea6a.png)
![image](https://user-images.githubusercontent.com/80534869/173242721-55d6eaf2-402d-43f3-8745-9c08c363796d.png)
![image](https://user-images.githubusercontent.com/80534869/173242745-3b6ddb6d-597a-4dfb-be4e-8d3377cd977f.png)

Okay now, I can see that the rock design is a bit found incomplete:
![image](https://user-images.githubusercontent.com/80534869/173242945-e3759088-8b30-4517-8883-9c5d5ef8fb03.png)

Orignal Footage SSK 95 Footage:
![image](https://user-images.githubusercontent.com/80534869/173242990-6470caf5-dc12-4063-ab4f-cb4c9d68647a.png)

Original B-ROLL' 95 Footage:
![image](https://user-images.githubusercontent.com/80534869/173243127-bc6f0d8f-5845-40d4-ba39-9040cf2a408a.png)

Look carefully you can see this dark or shadow polygon with a red circle.

Hopefully thanks for the reporting issue, you can do fix this beta WF level.

**Comment by xiartic** [comment]
Those lines in geometry are there in the actual game, just check for yourself. 
The UV for that wooden texture was that stretched, SW was not perfect.
![wood texture uv](https://user-images.githubusercontent.com/78692485/173245490-6bc47b63-2f6f-4301-a646-1b888e824ac8.PNG)

We're aware of the dirt geometry not perfectly matching up and it's listed in Trello which can be found in issues.
