### ISSUE TITLE
use leaked power meter code

### ISSUE THREAD

**Issue by s0lodolo** [Fluvian/tpp#53]

**Comment by TorutheRedFox** [comment]
it tends to break in emulators
(see https://github.com/gonetz/GLideN64/issues/2390)

**Comment by Fluvian** [comment]
The current code is already based on it.

**Comment by iProgramMC** [comment]
It doesn't look like it to me. There's a whopping three DLs associated with the early powermeter: `RCP_damegemeter_on`, `RCP_damegemeter_txt` and `RCP_damegemeter_off`.
