### ISSUE TITLE
Displaylist for actual Nintendo logo is slightly different

### ISSUE THREAD

**Issue by TorutheRedFox** [Fluvian/tpp#56]
this is a conversion of the n2u data using the leaked in house mbi->n2u->gbi converters to do so (can't remember the scale I used for it though as this was a while ago EDIT: it was 2.5x)

the logo is supposed to be 3D and flattened using guScale (I assume it's because it forces the RDP to antialias it better from what I remember, correct me if I'm wrong though)

[nintendo_logo.zip](https://github.com/Fluvian/tpp/files/8890470/nintendo_logo.zip)

**Comment by iProgramMC** [comment]
@TorutheRedFox GitHub has an option to adjust tab width

**Comment by TorutheRedFox** [comment]
still should be 4 by default like every normal editor does it

**Comment by TorutheRedFox** [comment]
plus that doesn't change it in comment code blocks

**Comment by Fluvian** [comment]
Could you describe the conversion process in more detail, I was able to get the tools to run with qemu-irix some time ago but I never used it to actually convert anything.

**Comment by TorutheRedFox** [comment]
the help document for n2u2gfx64 are pretty self explanatory relating syntax: n2u2gfx64 <switches> <n2u file> <a name of your choice for the model, not the filename>

as for nin2ultra16, you put in: nin2ultra16 nintendo_logo.c nintendo_logoVtx.c nintendo_logo (<-this is the filename without the extension) -d0 (<- some operation mode thing, dunno what it is but setting it to 0 works fine)

**Comment by TorutheRedFox** [comment]
so it's ```nin2ultra16 nintendo_logo.c nintendo_logoVtx.c nintendo_logo -d0```
then ```n2u2gfx64 nintendo_logo.n2u nintendo_logo```, which outputs a file named nintendo_logo_shape.sou

you probably have to use the -s option set to 10 though (10x scale) because of vertex precision (and the logo being quite small)

**Comment by iProgramMC** [comment]
> still should be 4 by default like every normal editor does it

```
	test
```

**Comment by TorutheRedFox** [comment]
a decompilation of these tools to make them a little _less_ annoying to use would be nice, but alas I'm not very good at reverse engineering MIPS assembly (or anything related to MIPS assembly)

**Comment by iProgramMC** [comment]
Someone else could pull an ido5.3_recomp on those tools

**Comment by iProgramMC** [comment]
@TorutheRedFox By the way, I think you should make a PR for this.

**Comment by TorutheRedFox** [comment]
actually yeah I should, but I gotta set up the build environment first xd

**Comment by TorutheRedFox** [comment]
oh forgot about the axis switching in the flags xd
