### ISSUE TITLE
Random baby penguin?

### ISSUE THREAD

**Issue by K-Dubs1** [Fluvian/tpp#58]
In snow slide, there's a random dud penguin in the corner. The mother does get mad if you pick it up in here vicinity. Is this done on purpose?
<img width="500" alt="Screen Shot 2022-06-13 at 9 32 20 PM" src="https://user-images.githubusercontent.com/77821101/173474784-320cfbb8-20da-4bb2-9fc0-a1da2e5a1ffe.png">
<img width="525" alt="Screen Shot 2022-06-13 at 9 34 37 PM" src="https://user-images.githubusercontent.com/77821101/173474792-e87e680d-528b-4d3b-9d33-97836fbac15b.png">

**Comment by Fluvian** [comment]
Yes
