### ISSUE TITLE
I noticed the text in the stage select menu is inaccurate.

### ISSUE THREAD

**Issue by legony64** [Fluvian/tpp#66]
This is the one from the Spaceworld demo
![image](https://user-images.githubusercontent.com/107322517/174207177-c3670bc7-0ec3-4a2d-885b-7929a2ee885d.png)
 
This is the one from TPP
![image](https://user-images.githubusercontent.com/107322517/174207239-be7180b0-a084-44e5-8a7c-856f9c46c43c.png)

**Comment by legony64** [comment]
> This is the one from the Spaceworld demo ![image](https://user-images.githubusercontent.com/107322517/174207177-c3670bc7-0ec3-4a2d-885b-7929a2ee885d.png)
> 
> This is the one from TPP ![image](https://user-images.githubusercontent.com/107322517/174207239-be7180b0-a084-44e5-8a7c-856f9c46c43c.png)

Alright just found out it was my plugin, lmao

**Comment by iProgramMC** [comment]
Please close the issue if this is resolved.
