### ISSUE TITLE
Remove assets that didn't exist in SW as they can cause memory to run out

### ISSUE THREAD

**Issue by TorutheRedFox** [Fluvian/tpp#67]
I've tried building multithreaded and single threaded, neither worked
there's no compiler errors or anything, and a binary does get built, but it crashes the emulator (Project64) right after the Nintendo logo

I'm able to build base decomp and my own projects just fine, and the patch also works without issue

**Comment by Fluvian** [comment]
The PR you made broke it since it takes up too much memory.

**Comment by TorutheRedFox** [comment]
wait it does?

well that's weird, it doesn't do that in my hack where I literally copy-pasted the changes from

**Comment by Fluvian** [comment]
I have no idea what breaks it, all the memory gets allocated before the Nintendo screen pops up, and it does pop up.

I preload the Goddard data before the logo pops up so it loads faster when switching from the logo to the head, as seen in footage, but that already allocates all it's memory before the logo pops up too, so I have no idea.

**Comment by TorutheRedFox** [comment]
time to search for bloat I guess then

**Comment by Fluvian** [comment]
https://github.com/Fluvian/tpp/blob/5bb23be687020d92dd46f5d802ceaea14b842e07/levels/intro/script.c#L21

Somewhere there is the culprit.

**Comment by TorutheRedFox** [comment]
I'll see how your changes behave in my hack

**Comment by TorutheRedFox** [comment]
ok it's even worse there
![image](https://user-images.githubusercontent.com/15708278/174398291-6344f4bc-9080-4a21-bc0f-a0e8cc0deb8b.png)

**Comment by TorutheRedFox** [comment]
it just does this immediately

**Comment by Fluvian** [comment]
Fix the `LOAD_RAW` calls as your leveldata is probably compressed.

**Comment by TorutheRedFox** [comment]
that made it even worse

before it played the sound, now it cuts out

**Comment by Fluvian** [comment]
Could you show what you changed?

**Comment by TorutheRedFox** [comment]
I've just copied the entirety of level_intro_entry_1 over to my hack to debug it and it's crashing even earlier

**Comment by Fluvian** [comment]
Change calls where segment 7 is referenced and `LOAD_RAW` is used to `LOAD_MIO0`.

`LOAD_RAW(/*seg*/ 0x07, _intro_segment_7SegmentRomStart, _intro_segment_7SegmentRomEnd),`

becomes

` LOAD_MIO0(/*seg*/ 0x07, _intro_segment_7SegmentRomStart, _intro_segment_7SegmentRomEnd),`

**Comment by TorutheRedFox** [comment]
I've made my own implementation and it seems that loading area 2 seems to cause this

**Comment by TorutheRedFox** [comment]
ok so I've decided to take a look at textures, remembering that SW never used the game over background

I found the textures, removed them from the segment and well... it works!

**Comment by TorutheRedFox** [comment]
creating a PR to remove them in a clean fashion rn

**Comment by TorutheRedFox** [comment]
https://github.com/Fluvian/tpp/pull/68

**Comment by TorutheRedFox** [comment]
the things simply deleting stuff can solve ;)

**Comment by iProgramMC** [comment]
Just a tip, but please test your changes in TPP before making PRs.

**Comment by TorutheRedFox** [comment]
I thought it was a misbuild (as those happen all the time with decomp, dunno why) and didn't have the time to rebuild it


oh and a tip for all working on any sort of beta hack: go through segments and levels, looking for textures, models, etc. that wouldn't have existed at that time in development, and remove them if possible. If it isn't, make the necessary code changes to make the game not depend on that data, and then delete it. In SM64 with without the Expansion Pak, especially with Nintendo's unoptimized af beta assets, memory is tight, and the simple presence of a texture that was used in the final game but didn't exist in the beta can break a build, as seen here.

In fact, I'll rename the issue for any other potential instances of such data.

**Comment by iProgramMC** [comment]
> I thought it was a misbuild (as those happen all the time with decomp, dunno why) and didn't have the time to rebuild it
> 
> oh and a tip for all working on any sort of beta hack: go through segments and levels, looking for textures, models, etc. that wouldn't have existed at that time in development, and remove them if possible. If it isn't, make the necessary code changes to make the game not depend on that data, and then delete it. In SM64 with without the Expansion Pak, especially with Nintendo's unoptimized af beta assets, memory is tight, and the simple presence of a texture that was used in the final game but didn't exist in the beta can break a build, as seen here.
> 
> In fact, I'll rename the issue for any other potential instances of such data.

Levels have already been removed. What's left is useless actors, animations and behavior data.

**Comment by TorutheRedFox** [comment]
levels don't take up memory unless they're actually loaded, plus from what I can tell, levels that didn't exist weren't completely removed, but had their slots populated by the dummy level

**Comment by iProgramMC** [comment]
They take up memory in ROM, though.

**Comment by TorutheRedFox** [comment]
ROM memory is quite plenty, our project, despite still being quite bloated with unused levels and actors, has multiple megabytes of padding

RAM is an issue though

**Comment by iProgramMC** [comment]
Well I guess you have padding because you still mio0 compress level data. TPP does not, so it has only about half a kilobyte left until it reaches 8 Mib

**Comment by TorutheRedFox** [comment]
oh right xddd

**Comment by TorutheRedFox** [comment]
the dummy and test levels don't take up much space afaik though

they'd only fit once the other bloat gets cut out though

**Comment by Fluvian** [comment]
There is not much "bloat" besides the actor data, which is a pain to remove and editing hundreds of files for a gain in ROM space is pointless since we are already under 8MB. Besides that every level is as optimized in RAM usage as possible already, since I always tested without the Expansion Pak.

**Comment by TorutheRedFox** [comment]
well it's not like using the expansion pak will help much if at all if SM64 only works within the 4MB regardless (without modifications)

**Comment by Fluvian** [comment]
I didn't say anything about using the Expansion Pak to help with anything.

I said I always tested within the constraints of NOT using one.

**Comment by TorutheRedFox** [comment]
I meant that whether you use the expansion pak or not, if the game isn't designed to use it, it won't change anything in most cases, and you'll run out of memory at the same point unless you dynamically allocate everything, which SM64 doesn't do

**Comment by Fluvian** [comment]
I meant without enabling the "extended memory" feature decomp has, then.

**Comment by TorutheRedFox** [comment]
ah

**Comment by iProgramMC** [comment]
> There is not much "bloat" besides the actor data, which is a pain to remove and editing hundreds of files for a gain in ROM space is pointless since we are already under 8MB. Besides that every level is as optimized in RAM usage as possible already, since I always tested without the Expansion Pak.

Could be doable by someone willing though.

**Comment by TorutheRedFox** [comment]
yeah

**Comment by TorutheRedFox** [comment]
removing actors can be started by replacing unused behaviorscripts with, which in itself saves a decent bit of memory
```
    BEGIN(OBJ_LIST_DEFAULT),
    OR_INT(oFlags, OBJ_FLAG_UPDATE_GFX_POS_AND_ANGLE),
    BREAK(),
```
