### ISSUE TITLE
aiff loop points?

### ISSUE THREAD

**Issue by TorutheRedFox** [Fluvian/tpp#69]
do the added/modified AIFFs have any loop points set? they don't sound like it

**Comment by TorutheRedFox** [comment]
use https://pastebin.com/qGdC4CHp to set them, otherwise samples will cut off if sustained/released for too long

**Comment by Fluvian** [comment]
I don't see the point of doing this. The ADPCM encoder just encodes the AIFF file, the loop points are all still controlled by software (sound_banks JSON files) and ADPCM files do not encode any loop points.

**Comment by TorutheRedFox** [comment]
the loop points are extracted into the AIFFs by the decomp tools, and then taken from them when building the banks

setloop sets the loop points in AIFF files in the format that the tools expect

without them, instruments that are supposed to loop until the ADSR fades the sample out end abruptly if it fades out after the loop ends, which is pretty audible (and inaccurate)

**Comment by Fluvian** [comment]
None of the instruments we changed besides the DDD lead uses any kind of looping, which sounds fine.

**Comment by TorutheRedFox** [comment]
it cuts off towards the end

hold on, I have a looped version (it's at 16khz though)
[TinePiano.k.16.c4.zip](https://github.com/Fluvian/tpp/files/8933563/TinePiano.k.16.c4.zip)
this, no matter how far you draw out the ADSR, will keep going until it fades out

**Comment by TorutheRedFox** [comment]
oneshot samples (i.e. drums) don't need loop points ,a s they don't sustain, but samples that do sustain do need them, as they can't sustain without them

**Comment by TorutheRedFox** [comment]
also side note: the water sequence loops a bit later than it's supposed to?

**Comment by TorutheRedFox** [comment]
I've drawn out the ADSR to illustrate my point

my sample keeps going, while yours ends abruptly on the higher notes (excuse the pops)

yours: https://www.youtube.com/watch?v=vzqZ01GXOfQ

mine: https://www.youtube.com/watch?v=cCDHD7aQqTc

note how mine keeps going and ends in unison when the notes get released, while yours cuts out before that happens at different times due to the different pitches and timing

**Comment by Fluvian** [comment]
Could you apply the proper loop timestamps to the AIFF that we have right now?

**Comment by TorutheRedFox** [comment]
I'll try

the thing is that with mine, I used the C5 sample as it's easier to loop due to having a less complex LFO pattern

**Comment by TorutheRedFox** [comment]
[26.zip](https://github.com/Fluvian/tpp/files/8933899/26.zip)
I also trimmed it as the part outside the loop end would not be played, like
ever
