### ISSUE TITLE
game crash

### ISSUE THREAD

**Issue by Supergub5871** [Fluvian/tpp#75]
so i was playing the rom hack then the game crashed heres a screenshot of where it crashed
![Screenshot 2022-07-03 102654](https://user-images.githubusercontent.com/90076568/177046425-9c222ffe-3235-4e77-9b1a-b9fbb4b46512.png)

**Comment by Fluvian** [comment]
You made that up like the last issue you made, if the game actually crashed there (which it didn't) it would show the crash handler.

**Comment by iProgramMC** [comment]
Perhaps this guy is using a plugin which does not support framebuffer emulation.

@Supergub5871 If you are able to reproduce this crash please do so with a plugin which supports framebuffer emulation (e.g. GLideN64)

**Comment by Supergub5871** [comment]
i am

**Comment by Supergub5871** [comment]
probly pj64 crash sorry
