### ISSUE TITLE
Game Over text does not appear.

### ISSUE THREAD

**Issue by JannGold** [Fluvian/tpp#78]
In the original beta, when you get a game over, it says game over in the same font as the press start text at the top of the screen with the standard background.

**Comment by Laffy-Taffy** [comment]
If I’m not mistaken, the game over text was simply edited on for the promotional footage.

**Comment by JannGold** [comment]
Was that the B-roll build?

**Comment by Laffy-Taffy** [comment]
I’m basing my assumption off the B-roll build, but if you have a video that shows that the Shoshinkai ‘95 demo actually had it, feel free to share.
