### ISSUE TITLE
Mario actually Jumps up, when he stops sliding, on his stomach

### ISSUE THREAD

**Issue by SeanKlaskyN64** [Fluvian/tpp#79]
When it comes to sliding, on the stomach, Mario actually jumps back up, in the real 1995 beta.

Source: https://www.youtube.com/watch?v=_k_i4wwEbjI
scroll the video at 4:12

**Comment by iProgramMC** [comment]
Check #76.

**Comment by SeanKlaskyN64** [comment]
I'll go ahead & take a look 👌

**Comment by Fluvian** [comment]
This is about animations, #3.
