### ISSUE TITLE
Windows not matching with proto SM64DS screenshots

### ISSUE THREAD

**Issue by CreamDream1943** [Fluvian/tpp#81]
The window and pond wall textures can be seen in screenshots taken from early builds of SM64DS, which appear to have a different look than what's seen in TPP.

![brick   window refs](https://user-images.githubusercontent.com/107242284/178952621-d358316f-03d1-4029-afd3-6b650848b3a9.png)

![Dsnitro_sm64ds](https://user-images.githubusercontent.com/107242284/178952652-b71dd2a5-9c4f-42a5-8dd8-c5cec41371cb.png)

Were these used as references? Going off the screenshots above, the color and decals should be updated. Sorry if this was already on a to-do list or smth

**Comment by K-Dubs1** [comment]
the wall texture is the same, the issue is the sm64ds model itself having a potentially different wall height and water placement leading to more being visible (there's also a poly missing in the sm64ds model that has the gravel texture regularly)
the windows seem to have the same color so i'd say those are alike

**Comment by CreamDream1943** [comment]
> the wall texture is the same, the issue is the sm64ds model itself having a potentially different wall height and water placement leading to the wall texture being more visible (there's also a poly missing in the sm64ds model that has the gravel texture regularly) the windows seem to have the same color so I'd say those are alike

I'm sorry, I thought the pond texture had slightly darker values than the recreation, but looking back it's clear that I was mistaken by the low resolution from distance, so apologies there.

![brick   window refs](https://user-images.githubusercontent.com/107242284/179094279-7d9d5121-dc73-4a2a-bba7-285314e80025.png)

![window ref](https://user-images.githubusercontent.com/107242284/179094369-3d90caaf-16b7-404e-9124-e0008f7fd02b.png)


However I still believe the windows are inaccurate, especially the color. Judging by these screenshots, the outer frame of the windows are less saturated grayish color, and the blinds are more saturated and bright. I don't think the low resolution would mess it that much, the colors actually seem to be different.
