### ISSUE TITLE
Game won't compile with WSL2 on Windows

### ISSUE THREAD

**Issue by SupercookieGIT** [Fluvian/tpp#83]
I keep getting this error whenever I try to compile using Ubuntu on WSL2:
`/usr/bin/env: ‘python3\r’: No such file or directory  
 Makefile:123: *** Failed to extract assets.  Stop.`

**Comment by iProgramMC** [comment]
I think you checked out the repository on windows? Check-out the repository in WSL2, that should fix it.

**Comment by SupercookieGIT** [comment]
It works now. Thanks.
