### ISSUE TITLE
Is TPP still being developed, or is it pull request only?

### ISSUE THREAD

**Issue by iProgramMC** [Fluvian/tpp#86]
Few commits have ever been done across this repo's history.. is this supposed to change? Has development stopped? Will we eventually get the snow slider finished? Just asking, because there hasn't been much activity and I'm wondering what's going on.

**Comment by Fluvian** [comment]
Well I'm *mostly* just working on it myself now and finding time and motivation to work on it is kind of hard especially after the time I've spent already working on it.

I'm also not great artistically so any help would appreciated, I'll upload the assets and if anyone wants to work on it and help that would be cool.

**Comment by iProgramMC** [comment]
Working alone is hard, yes, I've felt this way before. Sure, you can upload the assets if you like, then we may be able to help with more than code patches

**Comment by Fluvian** [comment]
> Well I'm _mostly_ just working on it myself now and finding time and motivation to work on it is kind of hard especially after the time I've spent already working on it.
> 
> I'm also not great artistically so any help would appreciated, I'll upload the assets and if anyone wants to work on it and help that would be cool.

https://drive.google.com/drive/folders/1-vIPVi-uixfjq6euc1EwaW28HoXcWv7r?usp=share_link
