### ISSUE TITLE
Window fix (UPDATED)

### ISSUE THREAD

**Issue by CreamDream1943** [Fluvian/tpp#87]
Updated my window texture, think it's more of an improvement now. More comparisons:

![93000a47-11d2-4c96-83c3-39a2fcb67393](https://user-images.githubusercontent.com/107242284/185770482-f3855e60-c48d-4462-9500-deb3f25b7421.gif)

![88802b20-6f9a-41d2-b8df-0b045b3c083a](https://user-images.githubusercontent.com/107242284/185770477-db4d429f-ad4b-4048-9bc2-86abe12838ff.gif)

![e959f487-14d5-4e63-acc9-f2a800a35c80](https://user-images.githubusercontent.com/107242284/185770478-30e3aa02-173c-466f-acfb-351a15e92bf6.gif)

updated again, background behind the blinds is darker now and the blinds themselves are thinner. 
![window](https://user-images.githubusercontent.com/107242284/185769887-38339451-e4d7-4a27-bb4f-0eedb86dba71.png)

Forgot to mention what I improved lol. Made both the border and blinds brighter as they appeared to be darker than they should be in relation to the inner frame's values.

**Comment by K-Dubs1** [comment]
The border of the window was brown, the project's seems to be correct.
<img width="88" alt="Screen Shot 2022-08-18 at 9 57 52 PM" src="https://user-images.githubusercontent.com/77821101/185525987-61e03067-db1f-4df6-86a3-6aa439cf22d7.png">

**Comment by CreamDream1943** [comment]
> The border of the window was brown, the project's seems to be correct. <img alt="Screen Shot 2022-08-18 at 9 57 52 PM" width="88" src="https://user-images.githubusercontent.com/77821101/185525987-61e03067-db1f-4df6-86a3-6aa439cf22d7.png">

Better?

![window](https://user-images.githubusercontent.com/107242284/185541444-a20b26b4-17c0-40c6-aa4f-c6ca35ac56c8.png)
