### ISSUE TITLE
More Accurate Pond Wall Texture

### ISSUE THREAD

**Issue by CreamDream1943** [Fluvian/tpp#89]
I've made my own pond wall recreation, which matches more closely with the patent and SM64x4 screenshots. Comparisons below.
Left: my recreation -- right: TPP

![632d73cb-ac3e-405a-8ef2-5425219dc237](https://user-images.githubusercontent.com/107242284/189175884-c51013de-e083-4586-8979-397b51623630.gif)

![4a19ddef-d694-4dab-b4be-928afc6e15fa](https://user-images.githubusercontent.com/107242284/189175904-4bebfa5c-08d4-4014-b249-189b7f0ca40d.gif)

okay last update
![pond walls](https://user-images.githubusercontent.com/107242284/189199656-fe5de786-1d3d-4d4f-9067-0102697e9986.png)

**Comment by Fluvian** [comment]
If you could make a pull request that would be nice.
