### ISSUE TITLE
FireBubble Land doesn't work

### ISSUE THREAD

**Issue by iProgramMC** [Fluvian/tpp#9]
There seems to be no collision at the spawn point of Firebubble Land.

![image](https://user-images.githubusercontent.com/17717494/172711343-048d873f-c447-4f80-8656-6a526a6f8623.png)

(This is not because of Project64, other people have encountered the same issue on other emulators.)

**Comment by Fluvian** [comment]
Should've clean-built the project locally...

**Comment by iProgramMC** [comment]
I downloaded the First Release.  Well, I also cloned the project, so I can do a build myself.

**Comment by iProgramMC** [comment]
> Should've clean-built the project locally...

A local build does not fix it.  I just tried.

**Comment by Fluvian** [comment]
What I meant is I should've checked more thoroughly. The latest commit fixes this.

**Comment by iProgramMC** [comment]
Nice, thanks!

**Comment by Peppe021203** [comment]
i tried the hotfix on console, the bug is still there
