### ISSUE TITLE
audiofile.h is missing when compile

### ISSUE THREAD

**Issue by MasterNama17083** [Fluvian/tpp#99]
![image](https://user-images.githubusercontent.com/80534869/202507969-d20e4724-baa0-4ee1-88bf-4e4a3b155f1d.png)
Okay so, I'm tried to build the source code but it says:
**"sdk-tools/tabledesign/tabledesign.c:5:10: fatal error: audiofile.h: No such file or directory"**
#
![image](https://user-images.githubusercontent.com/80534869/202508247-d9c256d6-51e3-43da-b522-eb7864c643a5.png)
I did skip with `audiofile.h` and then tried to compile just what happened.

**Comment by Fluvian** [comment]
Did you read the instructions? You need `libaudiofile-dev`.

Install it like this `sudo apt install build-essential pkg-config git binutils-mips-linux-gnu python3 zlib1g-dev libaudiofile-dev libcapstone-dev`.

**Comment by MasterNama17083** [comment]
Ah okay, it works. I installed `libaudiofile-dev` already did. Thanks np!
